#!/bin/python

# Author: Venkata Naga Sai Nivas Mangu
# Contact: sainonbeat99@gmail.com

# Import SQLite
import sqlite3

# Import sys for taking command line arguments
import sys

# Import functions for DB operations
from src.crud_functions import delete_all_finished_tasks, insert_tasks, read_tasks, update_tasks, delete_task, help
from src.wallpaper_functions import create_wallpaper

# Create connection to the database
connection = sqlite3.connect("./db/todo.db")
cursor = connection.cursor()

# Create a table in the database
create_table = """
CREATE TABLE IF NOT EXISTS todo(
  task_name TEXT UNIQUE,
  status BOOLEAN
)"""
cursor.execute(create_table)

# Define flag for insert_tasks
if len(sys.argv) > 1:
  if sys.argv[1] == "-i" or sys.argv[1] == "i" or sys.argv[1] == "--insert":
    try:
      insert_tasks(sys.argv[2])
      create_wallpaper()
    except IndexError:
      print("Not enough arguments. Enter the name of the task.")
      print("Try the -h flag for the help menu.")

  # Define flag for delete_task
  elif sys.argv[1] == "-d" or sys.argv[1] == "d" or sys.argv[1] == "--delete":
    try:
      delete_task(sys.argv[2])
      create_wallpaper()
    except IndexError:
      print("Not enough arguments. Enter the name of the task.")
      print("Try the -h flag for the help menu.")

  # Define flag for update_tasks
  elif sys.argv[1] == "-u" or sys.argv[1] == "u" or sys.argv[1] == "--update":
    update_tasks()
    create_wallpaper()

  # Delete all finished tasks
  elif sys.argv[1] == "-df" or sys.argv[1] == "df" or sys.argv[1] == "--delete-finished":
    delete_all_finished_tasks()
    create_wallpaper()

  # Define flag for help
  elif sys.argv[1] == "-h" or sys.argv[1] == "h" or sys.argv[1] == "--help":
    help()
else:
  print(read_tasks())